name: turtle
channels:
  - conda-forge
dependencies:
  - python>3
  - intake
  - intake-xarray
  - exiftool
  - scipy
  - scikit-learn
  - scikit-image
  - xarray
  - zarr
  - ipykernel
  - pip
  - pyproj
  - geopandas
  - gdal
  - pip:
    - pyexiftool
    - cameratransform


