fieldtrip : 'TR2023-01'
exiftool : exiftool
imagehead : "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw"
imagesource :  "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/"
marksource: "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/*.MRK"
obssource: "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/**/100_*/*_Rinex.obs"
possource: "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/**/100_*/*_Rinex.pos"
process: "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/process"
output :  "{CATALOG_DIR}/surveys"
imagewild : "*.JPG"
gnssceche : "{CATALOG_DIR}/{fieldtrip}/fielddata/p4rtk/raw/gnss"
surveyarea : "{CATALOG_DIR}/survey_area/"
labelmesource: "{CATALOG_DIR}/labelimage/turtle_json.csv"
reports : "{CATALOG_DIR}/surveys/reports"
country : AU
cameratype : RGB
dronetype: DJIP4
dewarp: [3706.080000000000,3692.930000000000,-34.370000000000,-34.720000000000,-0.271104000000,0.116514000000,0.001092580000,0.000348025000,-0.040583200000]
calibration : [3666.666504,2736,1824]

timedif : +08
timedelta : '20MIN'
basestation: EXMT00AUS
maxpitch: -70
mask: 25
gridsize: 5
outputhardlink : True

email : nick.mortimer@csiro.au  


mapboxkey : 'your mapboxkey'
